# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_base.ipynb.

# %% ../nbs/00_base.ipynb 1
from __future__ import annotations
import jax, jax.numpy as jnp, jax.random as jrand
import haiku as hk
import optax
import chex
from typing import Callable, Tuple, Any, Sequence, Iterable, Mapping, Dict, List, NamedTuple
import functools as ft
from .trainer import Trainer


# %% auto 0
__all__ = ['TrainState', 'StepFn']

# %% ../nbs/00_base.ipynb 2
class TrainState(NamedTuple):
    epoch: int
    step: int
    params: hk.Params
    state: hk.State
    opt_state: optax.OptState
    next_key: jrand.PRNGKey
    logs: dict = None

# %% ../nbs/00_base.ipynb 3
class StepFn:
    def __init__(self, trainer: Trainer, *args, **kwargs) -> None:
        self._trainer = trainer

    @property
    def trainer(self): return self._trainer

    @property
    def forward(self): return self.trainer.transformed
    
    @property
    def optimizer(self): return self.trainer.optimizers
