# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01_callbacks.ipynb.

# %% ../nbs/01_callbacks.ipynb 1
from __future__ import annotations
import jax, jax.numpy as jnp, jax.random as jrand
import haiku as hk
import optax
import chex
from typing import Callable, Tuple, Any, Sequence, Iterable, Mapping, Dict, List, NamedTuple
import functools as ft
from .trainer import TrainState, Trainer
from tqdm import tqdm

# %% auto 0
__all__ = ['Callback']

# %% ../nbs/01_callbacks.ipynb 2
class Callback:
    __every_n = 1
    __trainer: Trainer = None

    @property
    def every_n(self): return self.__every_n

    @property
    def trainer(self): return self.__trainer

    def every(self, n: int):
        self.__every_n = n
        return self
    
    def init_trainer(self, trainer: Trainer):
        self.__trainer = trainer
        return self
    
    def __call__(self, train_state: TrainState):
        raise NotImplementedError
